# Konfiguracja Cloudflare Pages

# Wymagana właściwość dla Cloudflare Pages
pages_build_output_dir = "angular-without-ssr/dist/angular-without-ssr/browser"

[build]
command = "cd angular-without-ssr && npm ci && npm run build:prod"

[build.environment]
NODE_VERSION = "20.11.1"

# Konfiguracja zmiennych środowiskowych produkcyjnych
[env.production]
NODE_ENV = "production"

# Konfiguracja zmiennych środowiskowych dla środowiska preview
[env.preview]
NODE_ENV = "production"
