# Konfiguracja Cloudflare Pages
name = "10xcards"

# Konfiguracja budowania
[build]
pages_build_output_dir = "angular-without-ssr/dist/angular-without-ssr/browser"
command = "./build-cloudflare.sh"

# Konfiguracja zmiennych środowiskowych produkcyjnych
[env.production]
NODE_VERSION = "20.11.1"
NODE_ENV = "production"

# Konfiguracja zmiennych środowiskowych dla środowiska preview
[env.preview]
NODE_VERSION = "20.11.1"
NODE_ENV = "production"
