name: 10xCards CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Umożliwia ręczne uruchomienie

jobs:
  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./angular-without-ssr
      NODE_VERSION: 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: npm ci

      - name: Setup environment
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Kopiowanie environments.default.ts do environments.ts
          cp src/environments/environments.default.ts src/environments/environments.ts
          echo "Skopiowano environments.default.ts do environments.ts"

      # Krok 1: Weryfikacja lintingu
      - name: Lint check
        working-directory: ${{ env.WORKING_DIR }}
        run: npm run lint || echo "Linting failed but continuing"

      # Krok 2: Testy jednostkowe
      - name: Run unit tests
        working-directory: ${{ env.WORKING_DIR }}
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      # Testy E2E usunięte

      # Krok 5: Build produkcyjny
      - name: Build production
        env:
          NODE_ENV: production
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENROUTER_KEY: ${{ secrets.OPENROUTER_KEY }}
          E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
          E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
        run: npm run build

      # Krok 6: Archiwizacja artefaktów
      - name: Archive production build
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: ${{ env.WORKING_DIR }}/dist/
          retention-days: 7

      # Krok 7: Archiwizacja raportów testów
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            ${{ env.WORKING_DIR }}/coverage/
          retention-days: 7
